sudo: required
dist: trusty
language: php
php:
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3
before_script:
- composer self-update
- composer install
script:
- CLIENT_ID=AdV4d6nLHabWLyemrw4BKdO9LjcnioNIOgoz7vD611ObbDUL0kJQfzrdhXEBwnH8QmV-7XZjvjRWn0kg CLIENT_SECRET=EPKoPC_haZMTq5uM9WXuzoxUVdgzVqHyD5avCyVC1NCIUJeVaNNUZMnzduYIqrdw-carG9LBAizFGMyK composer unit
